call plug#begin('~/.vim/plugged/')
call plug#end()

if has('nvim')
else
	set backspace=indent,eol,start
endif

set colorcolumn=+1

if has('persistent_undo')
	set undofile
	set undodir=~/.vim/undodir/
endif
set undolevels=2147483647
